name: Build & Push Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push se331-frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-frontend:latest
          build-args: |
            VITE_BACKEND_BASE=http://54.242.147.116:8999/api/v1

# name: Deploy to AWS Docker on merge

# on:
#   push:
#     branches:
#       - main

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Login to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-frontend:latest

#       - name: Copy docker-compose.yml via SSH
#         uses: appleboy/scp-action@v1
#         with:
#           host: ${{ secrets.HOST_SERVER }}
#           username: ${{ secrets.HOST_USER_NAME }}
#           key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
#           port: 22
#           source: "docker-compose.yml"
#           target: "/home/ubuntu/frontend"

#       - name: Deploy with Docker Compose
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.HOST_SERVER }}
#           username: ${{ secrets.HOST_USER_NAME }}
#           key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             cd /home/ubuntu/frontend
#             echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
#             docker compose down
#             docker compose pull
#             docker compose up -d
#             rm -rf /home/ubuntu/frontend
