name: Build & Push Frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'component-midterm-project/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push se331-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./component-midterm-project
          file: ./component-midterm-project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/se331-frontend:latest
          build-args: |
            VITE_BACKEND_BASE=http://98.93.104.161:8999/api/v1